version: '3.7'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    restart: always
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgresql://postgres:supersecretpassword@db/backend
    depends_on:
      - db
